config/routes.rb
Rails.application.routes.draw do
  resources :weekly_menus do
    member do
      get :copy
      put :copy
      post :copy
      delete :copy
    end
  end

  resources :meals

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'weekly_menus#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  validates :name, :side_dish, presence: true

  has_and_belongs_to_many :weekly_menu, optional: true
end

app/models/weekly_menu.rb
class WeeklyMenu < ApplicationRecord
  attr_accessor :meal_id, :name
  attr_readonly :start_date
  has_and_belongs_to_many :meals
  validates :meals, presence: true

  accepts_nested_attributes_for :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @weekly_menu = WeeklyMenu.find(params[:id])
    @meal = Meal.find(params[:id])
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :side_dish, :description)
    end
end

app/controllers/weekly_menus_controller.rb
class WeeklyMenusController < ApplicationController
  before_action :set_weekly_menu, only: %i[show edit update destroy]

  # GET /weekly_menus
  # GET /weekly_menus.json
  def index
    @weekly_menus = WeeklyMenu.all
  end

  # GET /weekly_menus/1
  # GET /weekly_menus/1.json
  def show; end

  # GET /weekly_menus/new
  def new
    @weekly_menu = WeeklyMenu.new
  end

  # GET /weekly_menus/1/edit
  def edit; end

  # POST /weekly_menus
  # POST /weekly_menus.json
  def create
    # Create weekly menu
    @weekly_menu = WeeklyMenu.new(weekly_menu_params)

    # For every meal select, create new entry in join table
    params[:weekly_menu][:meal_ids].each do |meal_id|
      unless meal_id.empty?
        meal = Meal.find(meal_id)
        @weekly_menu.meals << meal
      end
    end

    respond_to do |format|
      if @weekly_menu.save
        format.html { redirect_to @weekly_menu, notice: 'Weekly menu was successfully created.' }
        format.json { render :show, status: :created, location: @weekly_menu }
      else
        format.html { render :new }
        format.json { render json: @weekly_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weekly_menus/1
  # PATCH/PUT /weekly_menus/1.json
  def update
    params[:weekly_menu][:meal_ids].each do |meal_id|
      unless meal_id.empty?
        meal = Meal.find(meal_id)
        @weekly_menu.meals << meal
      end
    end

    respond_to do |format|
      if @weekly_menu.update(weekly_menu_params)
        format.html { redirect_to @weekly_menu, notice: 'Weekly menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_menu }
      else
        format.html { render :edit }
        format.json { render json: @weekly_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_menus/1
  # DELETE /weekly_menus/1.json
  def destroy
    @weekly_menu.destroy
    respond_to do |format|
      format.html { redirect_to weekly_menus_url, notice: 'Weekly menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Copies the start date of the menu
  def copy
    @original = WeeklyMenu.find(params[:id])
    @weekly_menu = @original.dup
    render 'new'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_weekly_menu
    @weekly_menu = WeeklyMenu.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def weekly_menu_params
    params.require(:weekly_menu).permit(:start_date, :meals_attributes => [:id, :name,:_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/weekly_menus_helper.rb
module WeeklyMenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenuBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Freshly</h1>
      <% end %>
    </div>

    <div class="navbar-menu">
      <div class="navbar-end">
        <div class="field is-grouped">
          <%= link_to 'All Menus', weekly_menus_path, class:"navbar-item button is-dark ml-4" %>
          <%= link_to 'All Meals', meals_path, class:"navbar-item button is-dark ml-4" %>
        </div>
      </div>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>

  <!-- Footer -->
  <footer class="page-footer font-small blue mt-5">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://www.freshly.com/">
        Freshly.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |form| %>
<% if meal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(meal.errors.count, "error") %>
      prohibited this meal from being saved:</h2>

    <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name, class: 'form-control-label' %>
  <%= form.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :side_dish, class: 'form-control-label'%>
  <%= form.text_field :side_dish, class: 'form-control' %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/meals/edit.html.erb
<h1 class="display-4 mb-4">Edit Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Show', @meal %>
|
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-center mb-4">Meals</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Side dish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.id %></td>
        <td><%= meal.name %></td>
        <td><%= meal.side_dish %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path, class: 'btn btn-primary' %>

app/views/meals/new.html.erb
<h1 class="display-4 mb-4">New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Side dish:</strong>
  <%= @meal.side_dish %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meal.description %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>

app/views/weekly_menus/_form.html.erb
<%= form_with(model: weekly_menu, local: true) do |form| %>
<% if weekly_menu.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(weekly_menu.errors.count, "error") %>
      prohibited this weekly_menu from being saved:</h2>

    <ul>
      <% weekly_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :start_date, class: 'form-control-label' %>
  <%= form.date_select :start_date, class: 'form-control' %>
</div>

<div class="control-group">
  <%= form.label :meals %>
  <%= collection_select(:weekly_menu, :meal_ids, Meal.all, :id, :name, {}, { :multiple => true } )%>
</div>

<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/weekly_menus/edit.html.erb
<h1 class="display-4 mb-4">Editing Weekly Menu</h1>

<%= render 'form', weekly_menu: @weekly_menu %>

<%= link_to 'Show', @weekly_menu %> |
<%= link_to 'Back', weekly_menus_path %>

app/views/weekly_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-center mb-4">Weekly Menus</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Start date</th>
      <th scope="col">Meals</th>
      <th scope="col">Number of Meals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weekly_menus.each do |weekly_menu| %>
      <tr>
        <td><%= weekly_menu.start_date.strftime("Starts on: %m/%d/%Y") %></td>
        <td><%= weekly_menu.meals.map(&:name).join(', ') %></td>
        <td><%= weekly_menu.meals.count %></td>
        <td><%= link_to 'Show', weekly_menu %></td>
        <td><%= link_to 'Edit', edit_weekly_menu_path(weekly_menu) %></td>
        <td><%= link_to 'Destroy', weekly_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weekly Menu', new_weekly_menu_path, class: 'btn btn-primary' %>

app/views/weekly_menus/new.html.erb
<h1 class="display-4 mb-4">New Weekly Menu</h1>

<%= render 'form', weekly_menu: @weekly_menu %>

<%= link_to 'Back', weekly_menus_path %>

app/views/weekly_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @weekly_menu.start_date %>
</p>

<%= link_to 'Edit', edit_weekly_menu_path(@weekly_menu) %>
|
<%= link_to 'Back', weekly_menus_path %>
|
<%= link_to "Copy", copy_weekly_menu_path(params[:id]) %>
|